/**
 * TSOA-Node-Express
 * TSOA-NodeExpress Documentation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IUserProfile } from './iUserProfile';


export interface IUserVm {
    id?: string;
    username: string;
    email: string;
    password?: string;
    createdOn?: Date;
    updatedOn?: Date;
    role?: string;
    lastVisited?: Date;
    profile?: IUserProfile;
}
