/**
 * TSOA-Node-Express
 * TSOA-NodeExpress Documentation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type UserRole = '0' | '1';

export const UserRole = {
    _0: '0' as UserRole,
    _1: '1' as UserRole
}
